---
title: "Data Dictionary"
format: html
editor: visual
---

## Summary of data tables

| Data table     | Description                                                                                                                                                      |
|----------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| project        | Project specific data, including dates, home port, vessel information, equipment used and equipment specifications                                               |
| operations     | Shipboard operations of survey equipment, including dates and times of HRG survey equipment ramp up, testing, and full power                                     |
| effort         | PSO monitoring effort, including dates, times, and lat/long of monitoring, type of monitoring (visual or acoustic), and weather and conditions during monitoring |
| visualdetect   | Summarizes visual detections of protected species, including species name, count of individuals, behavior of animals, and distance to boat and equipment         |
| acousticdetect | Summarizes acoustic detections of protected species, including species name, count of individuals, behavior of animals, and distance to boat and equipment       |
| portcall       | Describes vessel port calls and includes dates, times, and port name                                                                                             |
| PSOs           | Names and affiliations of protected species observers (PSOs) assigned to project                                                                                 |

# Data dictionary: project

Data dictionary for ***project*** data table

| Value               | Description                                                                                                                                                                            |
|---------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| PROJECT_NUMBER      | Offshore wind project number                                                                                                                                                           |
| PROJECT_NAME        | Name of offshore wind project                                                                                                                                                          |
| LEASE_NUM           | BOEM lease area number                                                                                                                                                                 |
| CLIENT              | Offshore Wind Developer                                                                                                                                                                |
| CONTRACTOR          | Company contracted to perform survey by developer                                                                                                                                      |
| VESSEL              | Name of survey vessel                                                                                                                                                                  |
| VESSEL_TYPE         | Type of vessel                                                                                                                                                                         |
| VESSEL_SIZE         | Size of vessel (meters)                                                                                                                                                                |
| VESSEL_SPEED        | Maximum speed of vessel (knots)                                                                                                                                                        |
| SURVEY_TYPE         | Type of survey being conducted (ex. HRG)                                                                                                                                               |
| COASTAL_ZONE        | State or coastal area survey is being conducted in                                                                                                                                     |
| PORT_START          | Departing port name                                                                                                                                                                    |
| PORT_END            | Returning port name                                                                                                                                                                    |
| REPORTING_START     | Reporting period start date                                                                                                                                                            |
| REPORTING_END       | Reporting period end date                                                                                                                                                              |
| SURVEY_EQUIP        | Survey equipment used (sparker, multibeam, sub-bottom profiler, sidescan-sonar)                                                                                                        |
| EQUIP_FREQ          | Frequency of survey equipment (kHz)                                                                                                                                                    |
| RMS_LEVEL           | Greatest RMS source level (dB)                                                                                                                                                         |
| SOFT_START          | Method of soft start of survey equipment                                                                                                                                               |
| MONITORING_EQUIP    | PSO visual monitoring equipment used (hand-held binoculars, big eyes, naked eye, infrared camera, hand-held NVD w/thermal)                                                             |
| MAGNIFICATION       | Magnification of optical equipment                                                                                                                                                     |
| HEIGHT              | Height of PSO eye off the water’s surface (meters)                                                                                                                                     |
| DISTANCE            | Method of measurement of distance to animal (by eye, with laser rangefinder, with rangefinder stick/calipers, with reticle binoculars, by relating to object at known distance, other) |
| PSO_TRAINING        | Training of PSOs (PSO training course for the Gulf of Mexico, BOEM/NMFS training for North Atlantic G&G, JNCC, other)                                                                  |
| PSO_VESSEL_LOCATION | Location of PSO on vessel during monitoring                                                                                                                                            |
| PSO_HEIGHT          | Height of PSO on vessel during monitoring                                                                                                                                              |
| PAM                 | Yes/no whether PAM was used during survey                                                                                                                                              |
| PAM_MANUFAC         | Manufacturer of PAM system                                                                                                                                                             |
| PAMGUARD            | Version of PAMGUARD utilized                                                                                                                                                           |
| DATE_PAMGUARD       | Date of initiated use of Pamguard version                                                                                                                                              |
| NUMBER_HYDRO        | Number of hydrophone elements                                                                                                                                                          |
| PAM_SERIAL          | Serial number of PAM equipment                                                                                                                                                         |
| DATE_PAM_ARRAY      | Date of PAMGUARD array                                                                                                                                                                 |

# Data dictionary: operations

Data dictionary for ***operations*** data table

| Value                  | Description                                                                           |
|------------------------|---------------------------------------------------------------------------------------|
| PROJECT_NUMBER         | Offshore wind project number                                                          |
| VESSEL                 | Name of survey vessel                                                                 |
| DATE                   | Date (MM/DD/YYYY)                                                                     |
| TIME_VIS_START         | Time of visual pre-clearance search began (UTC HH:MM)                                 |
| TIME_VIS_END           | Time of visual pre-clearance search ended (UTC HH:MM)                                 |
| DUR_VIS                | Duration of visual search (HH:MM)                                                     |
| TIME_ACOUS_START       | Time of acoustic pre-clearance search began (UTC HH:MM)                               |
| TIME_ACOUS_END         | Time of acoustic pre-clearance search ended (UTC HH:MM)                               |
| DUR_ACOUS              | Duration of acoustic search (HH:MM)                                                   |
| TIMEOFDAY              | Time of day of operations (day or night)                                              |
| PSO_REASON             | Yes/no whether there was any reason that protected species may not have been detected |
| HRG_SOURCE             | HRG sources used (sparker, sub-bottom profiler, etc)                                  |
| LINE_NUM               | Line and/or sequence number                                                           |
| RAMPUP_START           | Time of source ramp-up began (UTC HH:MM)                                              |
| RAMPUP_END             | Time of source ramp-up ended (UTC HH:MM)                                              |
| DUR_SOFTSTART          | Duration of soft start/ramp-up (HH:MM)                                                |
| EQUIP_DEPLOY_START     | Start time of equipment deployment (UTC HH:MM)                                        |
| EQUIP_DEPLOY_END       | End time of equipment deployment (UTC HH:MM)                                          |
| DUR_EQUIP_DEPLOY       | Duration of equipment deployment (HH:MM)                                              |
| TEST_START             | Time testing began (UTC HH:MM)                                                        |
| TEST_END               | Time testing ended (UTC HH:MM)                                                        |
| DUR_TEST               | Duration of testing (HH:MM)                                                           |
| SURVEY_START           | Time survey activity started (UTC HH:MM)                                              |
| SURVEY_END             | Time survey activity ended (UTC HH:MM)                                                |
| DUR_SURSOURCE          | Duration of survey source activity (HH:MM)                                            |
| DUR_PRESURSOURCE       | Duration of pre-survey source activity (HH:MM)                                        |
| FULLPOWER_END          | Time full power source activity ended (UTC HH:MM)                                     |
| DUR_POSTSUR            | Duration of post-survey source activity (HH:MM)                                       |
| REDUCEDSOURCE_START    | Time reduced source output began (UTC HH:MM)                                          |
| REDUCEDSOURCE_END      | Time reduced source output ended (UTC HH:MM)                                          |
| DUR_REDUCEDOUTPUT      | Duration of mitigation firing/reduced output firing (HH:MM)                           |
| EQUIP_RET_START        | Time equipment retrieval began (UTC HH:MM)                                            |
| EQUIP_RET_END          | Time equipment retrieval ended (UTC HH:MM)                                            |
| DUR_EQUIP_RET          | Duration of equipment retrieval (UTC)                                                 |
| MITIGATION_ACTION      | Yes/no whether mitigation action was required                                         |
| MITIGATION_TIME_CALLED | Time mitigation action was called (UTC HH:MM)                                         |
| MITIGATION_TIME_OCCUR  | Time mitigation occurred (UTC HH:MM)                                                  |
| COMMENT_OPERATIONS     | Comments about survey operations                                                      |

# Data dictionary: effort

Data dictionary for ***effort*** data table

| Value                | Description                                                                    |
|----------------------|--------------------------------------------------------------------------------|
| PROJECT_NUMBER       | Offshore wind project number                                                   |
| VESSEL               | Name of survey vessel                                                          |
| DATE                 | Date (MM/DD/YYYY)                                                              |
| TYPE                 | Effort type (visual, acoustic, or both VS day or night)                        |
| PSO_NUM              | Number of PSOs on visual watch                                                 |
| ACOUSTIC_MONITORING  | If acoustic, location of monitoring                                            |
| PAM_INITIALS         | PAM operator initials                                                          |
| PSO_INITIALS         | PSO initials                                                                   |
| VESSEL_ACTIVITY      | Activity of vessel                                                             |
| START_TIME           | Start of observations- time (UTC HH:MM)                                        |
| START_LAT            | Start of observations- latitude                                                |
| START_LONG           | Start of observations- longitude                                               |
| START_VESSELHEADING  | Start of observations- vessel heading (degrees)                                |
| START_VESSELSPEED    | Start of observations- vessel speed (knots)                                    |
| START_GIS_LAT        | Start of observations- GIS latitude                                            |
| START_GIS_LONG       | Start of observations- GIS longitude                                           |
| START_DEPTH          | Start of observations- water depth (meters)                                    |
| END_TIME             | End of observations- time (UTC HH:MM)                                          |
| END_LAT              | End of observations- latitude                                                  |
| END_LONG             | End of observations- longitude                                                 |
| END_VESSELHEADING    | End of observations- vessel heading (degrees)                                  |
| END_VESSELSPEED      | End of observations- vessel speed (knots)                                      |
| END_GIS_LAT          | End of observations- GIS latitude                                              |
| END_GIS_LONG         | End of observations- GIS longitude                                             |
| END_DEPTH            | End of observations- water depth (meters)                                      |
| VIS_DAY_OBS          | Duration of visual only (day) observations (HH:MM)                             |
| SOURCE_DAY_OBS       | Duration of source activity during visual only (day) observations (HH:MM)      |
| VIS_NIGHT_OBS        | Duration of visual only (night) observations (HH:MM)                           |
| SOURCE_NIGHT_OBS     | Duration of source activity during visual only (night) observations (HH:MM)    |
| PAM_DAY_OBS          | Duration of PAM only (day) monitoring (HH:MM)                                  |
| SOURCE_PAM_DAY       | Duration of source activity during PAM only (day) monitoring (HH:MM)           |
| PAM_NIGHT_OBS        | Duration of PAM only (night) monitoring (HH:MM)                                |
| SOURCE_PAM_NIGHT     | Duration of source activity during PAM only (night) monitoring (HH:MM)         |
| VIS_PAM_DAY_OBS      | Duration of visual and PAM (day) observations (HH:MM)                          |
| SOURCE_VIS_PAM_DAY   | Duration of source activity during visual and PAM (day) observations (HH:MM)   |
| VIS_PAM_NIGHT_OBS    | Duration of visual and PAM (night) observations (HH:MM)                        |
| SOURCE_VIS_PAM_NIGHT | Duration of source activity during visual and PAM (night) observations (HH:MM) |
| HYDRO_DEPTH          | For acoustic monitoring, hydrophone depth (meters)                             |
| WIND_SPEED           | Wind speed (knots)                                                             |
| WIND_DIR             | Wind direction                                                                 |
| BEAUF                | Beaufort Scale (0-12) (see Description Key for Beaufort Number)                |
| SWELL                | Swell height (meters)                                                          |
| VISIBIL              | Visibility (kilometers)                                                        |
| CLOUD                | Cloud coverage (%)                                                             |
| GLARE                | Glare off water                                                                |
| PRECIPI              | Precipitation (clear, haze, light rain, heavy rain)                            |
| COMMENT_EFFORT       | Comments about survey effort                                                   |
| HABITAT              | Habitat or prey type                                                           |
| PREY_LAT             | Prey observation latitude                                                      |
| PREY_LONG            | Prey observation longitude                                                     |
| MARINE_DEB           | Marine debris observed                                                         |
| MARINE_DEB_LAT       | Marine debris latitude                                                         |
| MARINE_DEB_LONG      | Marine debris longitude                                                        |
| PSO_VESSEL_LOCATION  | Location of PSO monitoring on vessel                                           |
| BLK_LABEL            |                                                                                |

# Data dictionary: visualdetect

Data dictionary for ***visualdetect*** data table

| Value                          | Description                                                                                                                                                                                                                                               |
|--------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| PROJECT_NUMBER                 | Offshore wind project number                                                                                                                                                                                                                              |
| VESSEL                         | Name of survey vessel                                                                                                                                                                                                                                     |
| DATE                           | Date (MM/DD/YYYY)                                                                                                                                                                                                                                         |
| VIS_DETECTION_NUM              | Visual detection number                                                                                                                                                                                                                                   |
| ACOUS_DETECTION_NUM            | Acoustic detection number if detection was correlated                                                                                                                                                                                                     |
| DETECT_FIRST                   | Time at first detection (UTC HH:MM)                                                                                                                                                                                                                       |
| DETECT_LAST                    | Time at last detection (UTC HH:MM)                                                                                                                                                                                                                        |
| PSO_NAME                       | Visual observer(s) name(s)                                                                                                                                                                                                                                |
| DETECT_MADE                    | How detection was first made (ex. visually during daylight by observer keeping a continuous watch)                                                                                                                                                        |
| DETECT_CUE                     | Detection cue- visual detectioundefinedns                                                                                                                                                                                                                 |
| LAT                            | Latitude                                                                                                                                                                                                                                                  |
| LONG                           | Longitude                                                                                                                                                                                                                                                 |
| GIS_LAT                        | GIS Latitude                                                                                                                                                                                                                                              |
| GIS_LONG                       | GIS Longitude                                                                                                                                                                                                                                             |
| VESSEL_HEADING                 | Compass heading of vessel (degrees)                                                                                                                                                                                                                       |
| DEPTH                          | Water depth (meters)                                                                                                                                                                                                                                      |
| BEAUF                          | Beaufort Scale (0-12) (see Description Key for Beaufort Number)                                                                                                                                                                                           |
| CLOUD                          | Cloud coverage (%)                                                                                                                                                                                                                                        |
| PRECIPI                        | Precipitation (clear, haze, light rain, heavy rain)                                                                                                                                                                                                       |
| NAME_COMMON                    | Animal common name                                                                                                                                                                                                                                        |
| NAME_SCI                       | Animal scientific name                                                                                                                                                                                                                                    |
| FAM                            | Animal family                                                                                                                                                                                                                                             |
| CERTAINTY                      | Certainty of identification                                                                                                                                                                                                                               |
| NUM_ADULT_HIGH                 | Number of adults detected-high estimate                                                                                                                                                                                                                   |
| NUM_ADULT_LOW                  | Number of adults detected-low estimate                                                                                                                                                                                                                    |
| NUM_ADULT_BEST                 | Number of adults detected- best estimate                                                                                                                                                                                                                  |
| NUM_JUV_HIGH                   | Number of juveniles detected-high estimate                                                                                                                                                                                                                |
| NUM_JUV_LOW                    | Number of juveniles detected-low estimate                                                                                                                                                                                                                 |
| NUM_JUV_BEST                   | Number of juveniles detected-best estimate                                                                                                                                                                                                                |
| TOT_NUM                        | Total number of individual animals detected                                                                                                                                                                                                               |
| DESCRIPTION                    | Visual description (include features such as overall size; shape of head; colour and pattern; size, shape, and position of dorsal fin; height, direction, shape of blow, sex/age if determinable, etc.)                                                   |
| BEHAVIOR_1                     | Behavior observed during the detection event                                                                                                                                                                                                              |
| BEHAVIOR_2                     | Behavior observed during the detection event                                                                                                                                                                                                              |
| BEHAVIOR_3                     | Behavior observed during the detection event                                                                                                                                                                                                              |
| BEHAVIOR_4                     | Behavior observed during the detection event                                                                                                                                                                                                              |
| BEHAVIOR_5                     | Behavior observed during the detection event                                                                                                                                                                                                              |
| BEHAVIOR_6                     | Behavior observed during the detection event                                                                                                                                                                                                              |
| DURATION_BOW_RIDING            | Total duration of bow-riding behavior, if behavior was observed (HH:MM)                                                                                                                                                                                   |
| BEARING_DETECT_CLOCKFACE_START | Relative bearing to the animal at initial detection (vessel bow is 0, clock face, 00:15-12:00)                                                                                                                                                            |
| BEARING_DETECT_DEG_START       | Relative bearing to the animal at initial detection (vessel bow is 0, in degrees)                                                                                                                                                                         |
| RANGE_VESSEL_START             | Range of animals to vessel at first detection (meters)                                                                                                                                                                                                    |
| RANGE_SOURCE_START             | Range of animals to source at first detection (meters)                                                                                                                                                                                                    |
| DIST_METHOD_START              | Method of distance determination at initial detection                                                                                                                                                                                                     |
| ANIMAL_HEAD_START              | Initial heading of animal(s) (degrees)                                                                                                                                                                                                                    |
| ANIMAL_PACE_START              | Animal(s) pace at initial detection (ex vigorous, moderate, sedate)                                                                                                                                                                                       |
| ANIMAL_DIRECT_VESSEL_START     | Direction of travel (relative to vessel) at initial detection                                                                                                                                                                                             |
| ANIMAL_DIRECT_EXCLUD_START     | Location/ direction of travel (relative to the Exclusion Zone) at initial detection                                                                                                                                                                       |
| BEARING_DETECT_CLOCKFACE_END   | Relative bearing to the animal at final detection (vessel bow is 0, clock face, 00:15-12:00)                                                                                                                                                              |
| BEARING_DETECT_DEG_END         | Relative bearing to the animal at final detection (vessel bow is 0, in degrees)                                                                                                                                                                           |
| RANGE_VESSEL_END               | Range of animals to vessel at last detection (meters)                                                                                                                                                                                                     |
| RANGE_SOURCE_END               | Range of animals to source at last detection (meters)                                                                                                                                                                                                     |
| DIST_METHOD_END                | Method of distance determination at final detection                                                                                                                                                                                                       |
| ANIMAL_HEAD_END                | Final heading of animal(s) (degrees)                                                                                                                                                                                                                      |
| ANIMAL_PACE_END                | Animal(s) pace at final detection  (ex vigorous, moderate, sedate)                                                                                                                                                                                        |
| ANIMAL_DIRECT_VESSEL_END       | Direction of travel (relative to vessel) at final detection                                                                                                                                                                                               |
| ANIMAL_DIRECT_EXCLUD_END       | Location/ direction of travel (relative to the Exclusion Zone) at final detection                                                                                                                                                                         |
| SOURCE_ACTIVITY_START          | Source activity at initial detection                                                                                                                                                                                                                      |
| SOURCE_ACTIVITY_END            | Source activity at final detection                                                                                                                                                                                                                        |
| MITZONE                        | Applicable mitigation zone (meters)                                                                                                                                                                                                                       |
| MITZONE_ANIMAL                 | Yes/no of whether the animal entered the mitigation zone during the detection event                                                                                                                                                                       |
| MITZONE_ANIMAL_COUNT           | Number of animals during the detection event observed inside the mitigation zone                                                                                                                                                                          |
| MITZONE_SOURCE                 | Yes/no of whether the source was active when the animals entered the mitigation zone                                                                                                                                                                      |
| MITZONE_ANIMAL_START           | Time animal entered mitigation zone (MZ) (UTC HH:MM)                                                                                                                                                                                                      |
| MITZONE_ANIMAL_END             | Time animal left mitigation zone (MZ) (UTC HH:MM)                                                                                                                                                                                                         |
| MITZONE_ACTIVESOURCE_DIST      | Closest distance of animals to active source (meters)                                                                                                                                                                                                     |
| MITZONE_ACTIVESOURCE_TIME      | Time at closest approach to active source (UTC HH:MM)                                                                                                                                                                                                     |
| MITZONE_SILENTSOURCE_DIST      | Closest distance of animals to silent source (meters)                                                                                                                                                                                                     |
| MITZONE_SILENTSOURCE_TIME      | Time at closest approach to silent source (UTC HH:MM)                                                                                                                                                                                                     |
| MITACTION                      | Source mitigation action required (none, shutdown of source, etc)                                                                                                                                                                                         |
| MITACTION_SHUTDOWN_CALL        | Time shutdown called for (UTC; HH:MM)                                                                                                                                                                                                                     |
| MITACTION_SHUTDOWN_START       | Time shutdown initiated  (UTC; HH:MM)                                                                                                                                                                                                                     |
| MIT_DOWNTIME                   | Mitigation downtime (HH:MM)                                                                                                                                                                                                                               |
| SEP_DISTANCE                   | Applicable separation distance (meters)                                                                                                                                                                                                                   |
| DIST_CLOSEST                   | Closest distance to the vessel (meters)                                                                                                                                                                                                                   |
| TIME_CLOSEST                   | Time at closest approach (UTC HH:MM)                                                                                                                                                                                                                      |
| TIME_SEPDISTANCE               | Time the animals entered the separation distance (UTC HH:MM)                                                                                                                                                                                              |
| AVOID_MANEUVER                 | Yes/no of whether avoidance maneuvers were conducted because animals entered the separation distance                                                                                                                                                      |
| AVOID_MANEUVER_TIME            | Time avoidance maneuvers conducted (if applicable) (UTC HH:MM)                                                                                                                                                                                            |
| OTHERVESSELS                   | Description of other vessels in the nearby vicinity (if any)                                                                                                                                                                                              |
| LEVEL_TAKE                     | Were any of the animals considered to be a "take"; if yes, what level                                                                                                                                                                                     |
| LEVELA_TAKE                    | Number of animals considered to be a Level A "take"                                                                                                                                                                                                       |
| LEVELB_TAKE                    | Number of animals considered to be a Level B "take"                                                                                                                                                                                                       |
| NARRATIVE                      | Visual Detection Narrative (including all information relevant to the detection, especially any changes in relation to source activity and distances from the source and EZ - times, distances, behaviors, locations, headings, mitigation actions, etc.) |
| PHOTOS                         | Photographs (with file names)                                                                                                                                                                                                                             |
| COMMENT_DETECTION_VISUAL       | Comments about visual detection                                                                                                                                                                                                                           |
| BLK_LABEL                      |                                                                                                                                                                                                                                                           |

# Data dictionary: acousticdetect

Data dictionary for ***acousticdetect*** data table

| Value                      | Description                                                                                                                                                                                                                                                              |
|----------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| PROJECT_NUMBER             | Offshore wind project number                                                                                                                                                                                                                                             |
| VESSEL                     | Name of survey vessel                                                                                                                                                                                                                                                    |
| DATE                       | Date (MM/DD/YYYY)                                                                                                                                                                                                                                                        |
| VIS_DETECTION_NUM          | Visual detection number (if detection was correlated)                                                                                                                                                                                                                    |
| ACOUS_DETECTION_NUM        | Acoustic detection number                                                                                                                                                                                                                                                |
| DETECT_FIRST               | Time at first detection (UTC HH:MM)                                                                                                                                                                                                                                      |
| DETECT_LAST                | Time at last detection (UTC HH:MM)                                                                                                                                                                                                                                       |
| PAM_NAME                   | Acoustic observer(s)                                                                                                                                                                                                                                                     |
| DETECT_MADE                | How detection was first made                                                                                                                                                                                                                                             |
| DETECT_CUE                 | Detection Cue - Acoustic Detection                                                                                                                                                                                                                                       |
| LAT                        | Latitude                                                                                                                                                                                                                                                                 |
| LONG                       | Longitude                                                                                                                                                                                                                                                                |
| GIS_LAT                    | GIS Latitude                                                                                                                                                                                                                                                             |
| GIS_LONG                   | GIS Longitude                                                                                                                                                                                                                                                            |
| VESSEL_HEADING             | Compass heading of vessel (degrees)                                                                                                                                                                                                                                      |
| DEPTH                      | Water depth (meters)                                                                                                                                                                                                                                                     |
| NAME_COMMON                | Animal common name                                                                                                                                                                                                                                                       |
| NAME_SCI                   | Animal scientific name                                                                                                                                                                                                                                                   |
| FAM                        | Animal family                                                                                                                                                                                                                                                            |
| CERTAINTY                  | Certainty of identification                                                                                                                                                                                                                                              |
| ANIMAL_HIGH                | Number of animals-high estimate                                                                                                                                                                                                                                          |
| ANIMAL_LOW                 | Number of animals-low estimate                                                                                                                                                                                                                                           |
| ANIMAL_BEST                | Number of animals-best estimate                                                                                                                                                                                                                                          |
| ACOUS_DESCRIPTION          | Acoustic description (including features of detection, such as type(s) of vocalization, spectral content, registered amplitudes, etc)                                                                                                                                    |
| ACOUS_DETECT_1             | Acoustic detection -the methods/modules on which vocalizations were detected during the event                                                                                                                                                                            |
| ACOUS_DETECT_2             | Acoustic detection -the methods/modules on which vocalizations were detected during the event                                                                                                                                                                            |
| ACOUS_DETECT_3             | Acoustic detection -the methods/modules on which vocalizations were detected during the event                                                                                                                                                                            |
| ACOUS_DETECT_4             | Acoustic detection -the methods/modules on which vocalizations were detected during the event                                                                                                                                                                            |
| ACOUS_DETECT_5             | Acoustic detection -the methods/modules on which vocalizations were detected during the event                                                                                                                                                                            |
| ACOUS_DETECT_6             | Acoustic detection -the methods/modules on which vocalizations were detected during the event                                                                                                                                                                            |
| BEARING_DETECT_DEG_START   | Bearing to animal(s) at first detection (degrees)                                                                                                                                                                                                                        |
| RANGE_HYDRO_START          | Range of animals to hydrophones at first detection (meters)                                                                                                                                                                                                              |
| RANGE_SOURCE_START         | Range of animals to source at first detection (meters)                                                                                                                                                                                                                   |
| DIST_METHOD_START          | Method of distance determination at initial detection                                                                                                                                                                                                                    |
| BEARING_DETECT_DEG_END     | Bearing to animal(s) at last detection (degrees)                                                                                                                                                                                                                         |
| RANGE_HYDRO_END            | Range of animals to hydrophones at last detection (meters)                                                                                                                                                                                                               |
| RANGE_SOURCE_END           | Range of animals to source at last detection (meters)                                                                                                                                                                                                                    |
| DIST_METHOD_END            | Method of distance determination at last detection                                                                                                                                                                                                                       |
| SOURCE_ACTIVITY_START      | Source activity at initial detection                                                                                                                                                                                                                                     |
| SOURCE_ACTIVITY_END        | Source activity at final detection                                                                                                                                                                                                                                       |
| MITZONE                    | Applicable mitigation zone (meters)                                                                                                                                                                                                                                      |
| MITZONE_ANIMAL             | Yes/no of whether the animal entered the mitigation zone during the detection event                                                                                                                                                                                      |
| MITZONE_SOURCE             | Yes/no whether the source was active when the animals entered the mitigation zone                                                                                                                                                                                        |
| MITZONE_ACTIVESOURCE_DIST  | Closest distance of animals to active source (meters)                                                                                                                                                                                                                    |
| MITZONE_ACTIVESOURCE_TIME  | Time at closest approach to active source (UTC HH:MM)                                                                                                                                                                                                                    |
| MITZONE_SILENTSOURCE_DIST  | Closest distance of animals to silent  source (meters)                                                                                                                                                                                                                   |
| MITZONE_SILENTSOURCE_TIME  | Time at closest approach to silent source (UTC HH:MM)                                                                                                                                                                                                                    |
| MITACTION                  | Source mitigation action required                                                                                                                                                                                                                                        |
| MIT_DOWNTIME               | Mitigation Downtime (HH:MM)                                                                                                                                                                                                                                              |
| NARRATIVE                  | Acoustic detection narrative (including all information relevant to the detection, especially any changes in relation to source activity and distances from the source and EZ - times, distances, bearings, tow depth of the hydrophone cable, mitigation actions, etc.) |
| FILES                      | Number of screengrabs and recordings (with file names)                                                                                                                                                                                                                   |
| COMMENT_DETECTION_ACOUSTIC | Comments on acoustic detection                                                                                                                                                                                                                                           |
| BLK_LABEL                  |                                                                                                                                                                                                                                                                          |

# Data dictionary: portcall

Data dictionary for ***portcall*** data table

| Value             | Description                               |
|-------------------|-------------------------------------------|
| PROJECT_NUMBER    | Offshore wind project number              |
| VESSEL            | Name of survey vessel                     |
| DATE              | Date (MM/DD/YYYY)                         |
| TIME              | Time of vessel action (UTC HH:MM)         |
| PORT              | Name of port                              |
| ACTION            | Vessel action (departing, arriving, etc.) |
| COMMENT_PORT_CALL | Comments on vessel activity, port call    |

# Data dictionary: PSOs

Data dictionary for ***PSOs*** data table

| Value            | Description                              |
|------------------|------------------------------------------|
| PROJECT_NUMBER   | Offshore wind project number             |
| VESSEL           | Name of survey vessel                    |
| PSO_NAME         | Name of Protected Species Observer (PSO) |
| PSO_AFFILIATION  | Affiliation/contract company of PSO      |
| PAM_NAME         | Name of Passive Acoustic Monitor (PAM)   |
| PAM_AFFILILATION | Affiliation/contract company of PAM      |

# Beaufort Scale

Description key for Beaufort Number

| Beaufort Number | Description     | Wave Height (m) | Sea Conditions                                                                                                                                                                                                                                                        |
|-----------------|-----------------|-----------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 0               | Calm            | 0               | Sea like a mirror                                                                                                                                                                                                                                                     |
| 1               | Light air       | 0-0.3           | Ripples with appearance of scales are formed, without foam crests                                                                                                                                                                                                     |
| 2               | Light breeze    | 0.3-0.6         | Small wavelets still short but more pronounced; crests have a glassy appearance but do not break                                                                                                                                                                      |
| 3               | Gentle breeze   | 0.6-1.2         | Large wavelets: crests begin to break; foam of glassy appearance; perhaps scattered white horses                                                                                                                                                                      |
| 4               | Moderate breeze | 1-2             | Small waves becoming longer; fairly frequent white horses                                                                                                                                                                                                             |
| 5               | Fresh breeze    | 2-3             | Moderate waves taking a more pronounced long form; many white horses are formed; chance of some spray                                                                                                                                                                 |
| 6               | Strong breeze   | 3-4             | Large waves begin to form; the white foam crests are more extensive everywhere; probably some spray                                                                                                                                                                   |
| 7               | High wind       | 4-5.5           | Sea heaps up and white foam from breaking waves begins to be blown in streaks along the direction of the wind; spindrift begins to be seen                                                                                                                            |
| 8               | Gale            | 5.5-7.5         | Moderately high waves of greater length; edges of crests break into spindrift; foam is blown in well-marked streaks along the direction of the wind                                                                                                                   |
| 9               | Severe gale     | 7-10            | High waves; dense streaks of foam along the direction of the wind; sea begins to roll; spray affects visibility                                                                                                                                                       |
| 10              | Storm           | 9-12.5          | Very high waves with long overhanging crests; resulting foam in great patches is blown in dense white streaks along the direction of the wind; on the whole the surface of the sea takes on a white appearance; rolling of the sea becomes heavy; visibility affected |
| 11              | Violent storm   | 11.5-16         | Exceptionally high waves; small- and medium-sized ships might be for a long time lost to view behind the waves; sea is covered with long white patches of foam; everywhere the edges of the wave crests are blown into foam; visibility affected                      |
| 12              | Hurricane force | \>14            | The air is filled with foam and spray; sea is completely white with driving spray; visibility very seriously affected                                                                                                                                                 |
